### PR TITLE
feat: add Docker Plugin releasing

### PR DESCRIPTION
**Pull request by tucksaun**
Related to https://github.com/grafana/loki/pull/9247#pullrequestreview-2416120537

Because Docker plugins are built using images but not shipped as images, the pipeline needs to be adjusted to consider this.
See https://docs.docker.com/engine/extend/#developing-a-plugin for more information about Docker plugins.

/cc @trevorwhitney

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
thank you!

**Comment by tucksaun** [comment]
@trevorwhitney you are welcome.

Regarding the failure, I don't think I can do much about it. Let me know if I can be of any assistance

**Comment by trevorwhitney** [comment]
@tucksaun yeah, that looks like that's on us. I'll look into it

**Comment by trevorwhitney** [comment]
closed in favor of #163, had to be run from `origin` to get the GH App ID

**Pull request closed without merging**
